name: Autograder

# Only runs when manually triggered
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Check out the test data
      - name: Checkout test_data
        run:  |
          echo "${{ secrets.DEPLOY_KEY }}"  | tr -d '\r' > ./deploy_key_zk
          chmod 600 ./deploy_key_zk
          export GIT_SSH_COMMAND="ssh -i ./deploy_key_zk -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

          mkdir -p autograde_data_zk
          git clone --filter=blob:none --no-checkout git@github.com:kurmasz-assignments/ag_test_data.git autograde_data_zk
          cd autograde_data_zk
          git sparse-checkout init --cone
          git sparse-checkout set CIS452/gvShell_v1
          git checkout main

      # Take a peek
      - name: Take a peek
        run: find .

      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"   # change to your Ruby version

      # Install dependencies (bundler and gems)
      - name: Install RSpec
        run: gem install rspec --no-document

      - name: Build with Make
        run: make

      # Run RSpec tests
      - name: Run RSpec
        run: rspec
