name: Autograder

# Only runs when manually triggered
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Check out the test data
      - name: Checkout test_data
        run:  |
          KEY_PATH=`pwd`/deploy_key_zk
          printf "%s\n" "${{ secrets.DEPLOY_KEY }}" > $KEY_PATH
          chmod 600 $KEY_PATH
          export GIT_SSH_COMMAND="ssh -i $KEY_PATH -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

          mkdir -p autograde_data_zk
          git clone --filter=blob:none --no-checkout git@github.com:kurmasz-assignments/ag_test_data.git autograde_data_zk
          cd autograde_data_zk
          git sparse-checkout init --cone
          git sparse-checkout set CIS452/gvShell_v1
          git checkout main
          mv CIS452/gvShell_v1/* .
          rm -rf CIS452

      # Take a peek
      - name: Take a peek
        run: find .

      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"   # change to your Ruby version

      # Install dependencies (bundler and gems)
      - name: Install RSpec
        run: gem install rspec --no-document

      - name: Build with Make
        run: make

      - name: Build helper
        run:  |
          gcc autograde_data_zk/debug_pipe.c -o debug_pipe_zk

      # Run RSpec tests
      - name: Run student's tests
        run: rspec

      - name: Run instructor tests
        run: rspec autograde_data_zk/spec
